# Generated by Django 5.1 on 2024-09-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                ("packageId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "packagename",
                    models.CharField(
                        default="Blank",
                        max_length=255,
                        null=True,
                        verbose_name="Package Name",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        default="Blank",
                        max_length=200,
                        null=True,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "dataoftour",
                    models.DateField(null=True, verbose_name="Date of Tour"),
                ),
                (
                    "price",
                    models.IntegerField(null=True, verbose_name="Price of Package"),
                ),
                (
                    "packagedescription",
                    models.CharField(
                        default="Blank",
                        max_length=10000,
                        null=True,
                        verbose_name="Package Description",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="",
                        null=True,
                        upload_to="packages/images",
                        verbose_name="Images",
                    ),
                ),
            ],
        ),
    ]
