# Generated by Django 5.1 on 2024-09-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("driverId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "drivername",
                    models.CharField(
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Driver Name",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        default="",
                        max_length=20,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="",
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "vehicle_name",
                    models.CharField(
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Vehicle Name",
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Vehicle Number",
                    ),
                ),
            ],
        ),
    ]
