# Generated by Django 5.1 on 2024-09-01 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_driver"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="dataoftour",
            new_name="dateoftour",
        ),
    ]
