# Generated by Django 5.1 on 2024-09-04 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="package_managament",
            new_name="package_management",
        ),
    ]
