# Generated by Django 5.1 on 2024-09-04 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_package_managament_profile_package_management"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="hotel_managament",
            new_name="hotel_management",
        ),
    ]
