# Generated by Django 5.1 on 2024-09-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_hotel_managament_profile_hotel_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(default='', max_length=255, null=True, verbose_name='Airline')),
                ('departure', models.CharField(default='', max_length=255, null=True, verbose_name='Departure Location')),
                ('destination', models.CharField(default='', max_length=255, null=True, verbose_name='Destination')),
                ('date_of_flight', models.DateField(null=True, verbose_name='Date of Flight')),
                ('price', models.IntegerField(null=True, verbose_name='Price of Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotelId', models.AutoField(primary_key=True, serialize=False)),
                ('hotelname', models.CharField(default='', max_length=255, null=True, verbose_name='Hotel Name')),
                ('location', models.CharField(default='', max_length=255, null=True, verbose_name='Location')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Rating')),
                ('price_per_night', models.IntegerField(null=True, verbose_name='Price Per Night')),
                ('hotel_description', models.CharField(default='', max_length=5000, null=True, verbose_name='Hotel Description')),
                ('image', models.ImageField(default='', null=True, upload_to='hotels/images', verbose_name='Images')),
            ],
        ),
    ]
