# Generated by Django 5.1 on 2024-09-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_airticket_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='airticket',
            name='airline_logo',
            field=models.ImageField(blank=True, null=True, upload_to='airline_logos/', verbose_name='Airline Logo'),
        ),
        migrations.AddField(
            model_name='airticket',
            name='flight_number',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Ticket Number'),
        ),
    ]
